export const Topics=[
  {
    id: "accident",
    keywords: ["road accident","car crash", "crash", "accident", "bike accident"],
    title: "Accident",
    url:"/accident",
  },
  {
    id: "allergic-reaction",
    keywords: ["allergy", "allergic reaction", "anaphylaxis", "epipen", "swelling"],
    title: "Allergy",
    url: "/allergy",
  },
  {
    id: "asthma",
    keywords: ["asthma", "asthma attack", "wheezing", "inhaler", "breathing issue"],
    title: "Asthma",
    url: "/asthma",
  },
  {
    id: "bleeding",
    keywords: ["bleed", "bleeding", "hemorrhage", "cut", "wound", "blood loss"],
    title: "Bleeding",
    url: "/bleeding",
  },
  {
    id: "burns",
    keywords: ["burn", "burns", "fire", "scald", "thermal injury"],
    title: "Burns",
    url: "/burns",
  },
  {
    id: "choking",
    keywords: ["choke", "choking", "airway", "blocked airway", "can't breathe"],
    title: "Choking",
    url: "/choking",
  },
  {
    id: "cpr",
    keywords: ["cpr", "cardiac arrest", "resuscitation", "no pulse", "unresponsive"],
    title: "CPR",
    url: "/cpr",
  },
  {
    id: "dog",
    keywords: ["dog bite","dog", "rabies"],
    title: "Dog Bite",
    url:"/dogbite",
  },
  {
    id: "drowning",
    keywords: ["drowning", "near drowning", "water inhalation", "can't swim"],
    title: "Drowning",
    url: "/drowning",
  },
  {
    id: "electric-shock",
    keywords: ["electric shock", "electrocution", "current", "electric burn"],
    title: "Electric Shock",
    url: "/electric-shock",
  },
  {
    id: "fainting",
    keywords: ["faint", "fainting", "syncope", "passed out", "lightheaded"],
    title: "Fainting",
    url: "/fainting",
  },
  {
    id: "fracture",
    keywords: ["fracture", "broken bone", "bone injury", "crack", "limb injury"],
    title: "Fracture",
    url: "/fracture",
  },
  {
    id: "head-injury",
    keywords: ["head injury", "concussion", "hit head", "brain injury"],
    title: "Head Injury",
    url: "/head-injury",
  },
  {
    id: "heart-attack",
    keywords: ["heart attack", "chest pain", "myocardial infarction", "cardiac"],
    title: "Heart Attack",
    url: "/cpr",
  },
  {
    id: "heatstroke",
    keywords: ["heat stroke", "heat exhaustion", "hot weather", "dehydration"],
    title: "Heatstroke",
    url: "/heatstroke",
  },
  {
    id: "hypothermia",
    keywords: ["hypothermia", "cold exposure", "freezing", "low body temp"],
    title: "Hypothermia",
    url: "/hypothermia",
  },
  {
    id: "nosebleed",
    keywords: ["nosebleed", "bleeding nose", "bloody nose", "nasal bleed"],
    title: "Nosebleed",
    url: "/nosebleed",
  },
  {
    id: "poisoning",
    keywords: ["poison", "toxins", "chemical ingestion", "swallowed", "poisoning"],
    title: "Poisoning",
    url: "/poisoning",
  },
  {
    id: "seizure",
    keywords: ["seizure", "epilepsy", "convulsions", "fits", "uncontrolled shaking"],
    title: "Seizure",
    url: "/seizure",
  },
  {
    id: "snake",
    keywords: ["snake bite","snake", "venom"],
    title: "Snake Bite",
    url:"/snakebite",
  },
  {
    id: "sprain",
    keywords: ["sprain", "strain", "twisted ankle", "joint injury"],
    title: "Sprain",
    url: "/sprain",
  },
  {
    id: "stroke",
    keywords: ["stroke", "face droop", "slurred speech", "brain attack", "FAST"],
    title: "Stroke",
    url: "/stroke",
  }
];
